# Data

* Sources
* Description
* Wrangling/cleaning
* Spotting mistakes and missing data (could be part of EDA too)
* Listing anomalies and outliers (could be part of EDA too)

```{r}
library(here)
directory <- here("data")

properties <- read.csv(file.path(directory,"properties.csv"))

metrecarré <- read.csv(file.path(directory,"snb-data-plimoincha-fr-all-20240321_0900.csv"))
# Assuming your data frame is named metrecarré
metrecarré <- metrecarré[-1, ]

split_data <- lapply(metrecarré, function(x) unlist(strsplit(as.character(x), ";")))

split_df <- do.call(rbind, split_data)
```

```{r}
#install.packages("readxl")
library(readxl)

# Read the cpi file
cpi_data_excel <- read_excel(file.path(directory,"cpi.xlsx"))
# Write the data to a CSV file
write.csv(cpi_data_excel, file.path(directory,"cpi.csv"), row.names = FALSE)
# Load the CSV file into a data frame
cpi <- read.csv(file.path(directory,"cpi.csv"))


# Read the empty_dwellings file
empty_excel <- read_excel(file.path(directory,"empty_dwellings_by_canton_1999-2023.xlsx"))
# Write the data to a CSV file
write.csv(empty_excel, file.path(directory,"empty_dwellings.csv"), row.names = FALSE)
# Load the CSV file into a data frame
empty_dwellings <- read.csv(file.path(directory,"empty_dwellings.csv"))
```

