---
title: "EDA properties"
author: "Hugo Troendle, Urs Huerni, Léo Wenger"
format: html
editor: visual
embed-resources: true
editor: visual
self-contained: true
toc: true
toc-depth: 2
toc-location: left
---


```{r, warning=FALSE}
#| code-fold: true
#| code-summary: "Click to show code"
# Load required libraries
library(ggplot2)
library(plotly)
here::set_here()
```

## Histogram of Prices

```{r, warning=FALSE}
#| code-fold: true
#| code-summary: "Click to show code"
histogram_price <- ggplot(properties_filtered, aes(x = price)) +
  geom_histogram(binwidth = 100000, fill = "skyblue", color = "red") +
  labs(title = "Distribution of Prices", x = "Price")
interactive_histogram_price <- ggplotly(histogram_price)
interactive_histogram_price
```

## Histogram of Prices by Property Type

Note: Only prices between 0 and 500000 are included to exclude outliers.

```{r, warning=FALSE}
#| code-fold: true
#| code-summary: "Click to show code"
histogram <- ggplot(properties_filtered, aes(x = price)) +
  geom_histogram(binwidth = 100000, fill = "skyblue", color = "black") +
  facet_wrap(~ property_type, scales = "free", ncol = 2) +
  labs(title = "Distribution of Prices by Property Type")
interactive_histogram <- ggplotly(histogram)
interactive_histogram
```

## Histogram of Prices by Year Category

Note: Only prices between 0 and 500000 are included to exclude outliers.

```{r, warning=FALSE}
#| code-fold: true
#| code-summary: "Click to show code"
histogram_year <- ggplot(properties_filtered, aes(x = price)) +
  geom_histogram(binwidth = 100000, fill = "skyblue", color = "black") +
  facet_wrap(~ year_category, scales = "free", ncol = 2) +
  labs(title = "Distribution of Prices by Year Category")
interactive_histogram_year <- ggplotly(histogram_year)
interactive_histogram_year
```

## Test Regression

```{r}
#| code-fold: true
#| code-summary: "Click to show code"
# Perform multiple linear regression
model <- lm(price ~ number_of_rooms + canton + property_type + year_category, data = properties_filtered)
```
